config/routes.rb
Rails.application.routes.draw do
  resources :civic_tech_applications, only: [:show, :index]
  root to: 'civic_tech_applications#index'
end

app/models/app_type_tag.rb
class AppTypeTag < Tag
  has_and_belongs_to_many :civic_tech_applications,
                          association_foreign_key: 'civic_tech_application_id',
                          join_table: 'civic_tech_applications_tags'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/civic_tech_application.rb
class CivicTechApplication < ApplicationRecord
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :tech_tags,
                          association_foreign_key: 'tag_id',
                          join_table: 'civic_tech_applications_tags'
  has_and_belongs_to_many :contest_tags,
                          association_foreign_key: 'tag_id',
                          join_table: 'civic_tech_applications_tags'
  has_and_belongs_to_many :app_type_tags,
                          association_foreign_key: 'tag_id',
                          join_table: 'civic_tech_applications_tags'
  has_and_belongs_to_many :license_tags,
                          association_foreign_key: 'tag_id',
                          join_table: 'civic_tech_applications_tags'
end

app/models/contest_tag.rb
class ContestTag < Tag
  has_and_belongs_to_many :civic_tech_applications,
                          association_foreign_key: 'civic_tech_application_id',
                          join_table: 'civic_tech_applications_tags'
end

app/models/license_tag.rb
class LicenseTag < Tag
  has_and_belongs_to_many :civic_tech_applications,
                          association_foreign_key: 'civic_tech_application_id',
                          join_table: 'civic_tech_applications_tags'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :civic_tech_applications
end

app/models/tech_tag.rb
class TechTag < Tag
  has_and_belongs_to_many :civic_tech_applications,
                          association_foreign_key: 'civic_tech_application_id',
                          join_table: 'civic_tech_applications_tags'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/civic_tech_applications_controller.rb
class CivicTechApplicationsController < ApplicationController
  before_action :set_civic_tech_application, only: [:show, :edit, :update, :destroy]

  # GET /civic_tech_applications
  # GET /civic_tech_applications.json
  def index
    @civic_tech_applications = CivicTechApplication.all
  end

  # GET /civic_tech_applications/1
  # GET /civic_tech_applications/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_civic_tech_application
    @civic_tech_application = CivicTechApplication.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/civic_tech_applications_helper.rb
module CivicTechApplicationsHelper
  def tag_type_css_map(type)
    {
      ''           => 'btn btn-primary mb-1',
      'TechTag'    => 'btn btn-secondary mb-1',
      'ContestTag' => 'btn btn-success mb-1',
      'AppTypeTag' => 'btn btn-info mb-1',
      'LicenseTag' => 'btn btn-dark mb-1'
    }[type.to_s] || 'btn btn-danger mb-1'
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/civic_tech_applications/_form.html.erb
<%= form_with(model: civic_tech_application, local: true) do |form| %>
  <% if civic_tech_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(civic_tech_application.errors.count, "error") %> prohibited this civic_tech_application from being saved:</h2>

      <ul>
      <% civic_tech_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/civic_tech_applications/edit.html.erb
<h1>Editing Civic Tech Application</h1>

<%= render 'form', civic_tech_application: @civic_tech_application %>

<%= link_to 'Show', @civic_tech_application %> |
<%= link_to 'Back', civic_tech_applications_path %>

app/views/civic_tech_applications/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Civic Tech Application & OpenData カタログ</h1>
    <p>シビックテックアプリやオープンデータのカタログサイトです。 by <a href="https://github.com/PharaohKJ">@PharaohKJ</a></p>
    <p>本サイトのアイデアは <a href="https://2018.civictechforum.jp">CIVIC TECH FORUM 2018</a> にてブレストされた「他自治体に所属するみんなで充分に開発されているアプリの一覧性・検索性を向上することで、再度開発しちゃうことを防ぐ・元コードやデータに貢献する人を増やせるのではないか？」というアイデアが発端です。</p>
      <p>いまのところ @PharaohKJ が勝手にデータを追加しています。アプリケーション・オープンデータの製作者に掲載許可はとっておりません。</p>
    <p>ですが、掲載してほしいなどありましたらぜひご連絡ください。How To Contributes は後日かきますが、アプリ説明のfixture(YAML形式)を書いていただいてプルリクしていただこうと考えています。 </p>
    <p>ほかにも機能追加などご要望ありましたら GitHub issue 経由でご連絡ください。</p>
    <p><a class="btn btn-dark btn-lg" href="https://github.com/PharaohKJ/CivictechAppCatalog" role="button">GitHubへ »</a></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @civic_tech_applications.each do |cta| %>
      <div class="col-md-6 mb-4">
        <h2><%= link_to cta.name, civic_tech_application_path(cta) %></h2>
        <%= simple_format(cta.description) %>
        <% cta.tags.each do |t| %>
          <%= link_to t.name, '', class: tag_type_css_map(t.type) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/civic_tech_applications/new.html.erb
<h1>New Civic Tech Application</h1>

<%= render 'form', civic_tech_application: @civic_tech_application %>

<%= link_to 'Back', civic_tech_applications_path %>

app/views/civic_tech_applications/show.html.erb
<p id="notice"><%= notice %></p>
<% app = @civic_tech_application %>
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3"><%= app.name%></h1>
    <h3><%= link_to( app.url, app.url )%></h2>
    <%= simple_format(app.description) %>
      <% app.tags.each do |t| %>
        <%= link_to t.name, '', class: tag_type_css_map(t.type) %>
      <% end %>
    </p>
  </div>
</div>

<div class="container">
  <div class="row">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CivictechAppCatalog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main role="role">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.type %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @tag.type %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>